apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-multi-container-pod
  labels:
    app: mcpod
spec:
  containers:
  - name: nodejs-express-backend 
    image: gcr.io/$GCP_PROJECT/nodejs-express-backend:v1
  - name: nodejs-express-api
    image: gcr.io/$GCP_PROJECT/nodejs-express-api:v1
    ports:
    - containerPort: 8080
